apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playgroundbot.fullname" . }}
  labels:
    {{- include "playgroundbot.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.botToken | required "botToken is required" | b64enc }}